[[questions]]
question = "What is an Euler path?"
answer = "A path that visit every edge exactly once."

[[questions]]
question = "What is an Euler circuit?"
answer = "A path that visits every edge exactly once and starts and ends at the same vertex."